### ISSUE TITLE
All services should have a db.MaxOpenConns set

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/service#1058]
Caused: https://github.com/weaveworks/service/issues/1055, but could potentially cause similar issues on other services.

## TODO

- [ ] Add max_open_conns flag to all services
  - [ ] cortex/configs
  - [ ] flux/fluxsvc
  - [ ] monitoring/prose
  - [ ] prometheus db exporter for bonus points
- [ ] Add the query param to all remaining services
