### ISSUE TITLE
Security Umbrella Issue

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/service#1069]
Reported vulnerabilities: 
- [x] CSRF (~https://github.com/weaveworks/service/issues/2~ #1072)
- [x] Click Jacking (https://github.com/weaveworks/service/issues/1062)
- [x] Open Redirect (https://github.com/weaveworks/service/issues/1068)
- [x] Oauth problem (#1081)
- [x] Logout doesn't (https://github.com/weaveworks/service/issues/1064)
- [x] Make cloud.weave.works https-only, and other Mozilla observatory stuff (https://github.com/weaveworks/service/issues/1106)
