### ISSUE TITLE
Audit system for SPOFs

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/service#150]
SPOFs I can think of:
- [x] <s>Only one replica of each component in prod (#173 Increase replicas of services in dev and prod.)</s>
- [x] <s>Restart containers when they fail (#136)</s>
- [x] We don't restart containers (user apps) on failed hosts (#160 Investigate proper container scheduling platform)
- [x] Swarm master (#95 Deploy Swarm HA)
- RDS instances (#149 Setup RDS replication)
- [ ] We're not necessarily deployed across multiple AZs
- We're only in a single region (#184)

And disaster recovery:
- [x] Enable RDS backups
- [x] Script up completely rebuilding the setup, including setup users application
