### ISSUE TITLE
Release GCP Cloud Launcher integration

### ISSUE THREAD

**Issue by marccarre** [weaveworks/service#1566]
- [x] ensure we can create/assign/close issues in [Google's Issue Tracker](https://partnerissuetracker.corp.google.com/issues?q=status:open%20componentid:326549&s=created_time:desc)
- [x] add configuration in `service-conf` for `prod`: weaveworks/service-conf/pull/1606
- [x] create Grafana dashboard to plot metrics exposed by `gcp-launcher-webhook` https://github.com/weaveworks/service-conf/pull/1614
- [x] create alerts in case of "too many" errors in `gcp-launcher-webhook` (moved to #1620)
- [x] (after Dec 4th) activate GCP Pub/Sub subscription for `prod`, i.e.:

    - [delete the `dev` subscription](https://console.cloud.google.com/cloudpubsub/subscriptions?project=weaveworks-public&organizationId=36144081350) and
    - create the `prod` one with the below command: 

            gcloud beta pubsub subscriptions create prod --topic=weaveworks-public-cloudmarketplacepartner.googleapis.com --topic-project=cloud-billing-subscriptions --push-endpoint=https://cloud.weave.works/api/gcp-launcher/webhook?secret=<webhookSecret base64 decoded>

- [x] (after Dec 4th) configure signup URL to point to `prod` in [GCP Partner Portal](https://console.cloud.google.com/partner/editor/weaveworks-public/weave-cloud?project=weaveworks-public)
  * Requires email to Tate

- [x] (after Dec 4th) configure SSO URL to point to `prod` in [GCP Partner Portal](https://console.cloud.google.com/partner/editor/weaveworks-public/weave-cloud?project=weaveworks-public)
  * Requires email to Tate

- [x] training session for engineering (moved to #1618)
- [x] convert [Partner API CLI](https://github.com/weaveworks/service/pull/1562) to a page/form in the admin UI section (moved to #1619)
- [x] Google makes it available to the public
