### ISSUE TITLE
Implement all permission checks

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/service#2125]
The user service is somewhat central to instance access and permissions. We should make sure its entrypoints are correctly guarded with the right permissions, possibly with some unit-tests.

### Backend

* [x] `team.member.invite` - #2463
* [x] `team.member.update` - #2468
* [x] `team.member.remove` - #2468
* [x] `team.members.view` - #2468
* [x] `instance.delete` - #2463
* [x] `instance.transfer` - #2468
* [x] `instance.billing.update` - #2463
* [ ] `instance.token.view`
* [x] `notification.settings.update` - #2468
* [x] `alert.settings.update` - #2463
* [x] `notebook.create` - #2468
* [x] `notebook.update` - #2468
* [x] `notebook.delete` - #2468
* [x] `scope.host.exec` - #2468
* [x] `scope.container.exec` - #2468
* [ ] `scope.container.attach.in`
* [x] `scope.container.attach.out` - #2468
* [x] `scope.replicas.update` - #2468
* [x] `scope.pod.delete` - #2468
* [x] `flux.image.deploy` - #2468
* [x] `flux.policy.update` - #2468

### Frontend

* [x] `team.member.invite` - https://github.com/weaveworks/service-ui/pull/3611
* [x] `team.member.update` - https://github.com/weaveworks/service-ui/pull/3611
* [x] `team.member.remove` - https://github.com/weaveworks/service-ui/pull/3611
* [x] `team.members.view` - https://github.com/weaveworks/service-ui/pull/3611
* [x] `instance.delete` - https://github.com/weaveworks/service-ui/pull/3611
* [x] `instance.transfer` - https://github.com/weaveworks/service-ui/pull/3611
* [x] `instance.billing.update` - https://github.com/weaveworks/service-ui/pull/3613
* [x] `instance.token.view` - https://github.com/weaveworks/service-ui/pull/3613
* [x] `alert.settings.update` - https://github.com/weaveworks/service-ui/pull/3613
* [x] `notification.settings.update` - https://github.com/weaveworks/service-ui/pull/3613
* [x] `notebook.create` - https://github.com/weaveworks/service-ui/issues/3616
* [x] `notebook.update` - https://github.com/weaveworks/service-ui/issues/3616
* [x] `notebook.delete` - https://github.com/weaveworks/service-ui/issues/3616
* [x] `scope.host.exec` - https://github.com/weaveworks/service-ui/pull/3619
* [x] `scope.container.exec` - https://github.com/weaveworks/service-ui/pull/3619
* [ ] `scope.container.attach.in`
* [x] `scope.container.attach.out` - https://github.com/weaveworks/service-ui/pull/3619
* [x] `scope.replicas.update` - https://github.com/weaveworks/service-ui/pull/3619
* [x] `scope.pod.delete` - https://github.com/weaveworks/service-ui/pull/3619
* [x] `flux.image.deploy` - https://github.com/weaveworks/service-ui/pull/3615
* [x] `flux.policy.update` - https://github.com/weaveworks/service-ui/pull/3615
