### ISSUE TITLE
Default alerts/notifications to email

### ISSUE THREAD

**Issue by fbarl** [weaveworks/service#2140]
From the [Scope doc](https://docs.google.com/document/d/101C7jqBptVzUuI84UWe9S2AIgSXWHsynAW4pZaSn_sU/edit#heading=h.strhhel78co4):

> The platform is too quiet and doesn’t tell the user why it’s valuable and what it’s doing for them, encourage people to come back by sending them alerts/notifications emails.

> Ensure default notifications and alerts are sent to the user by email.

Must:
* [x] Allow users to configure more than one email address to receive notifications
* [x] ~Include a links to metrics, active alerts, and to where alerts can be configured~ https://github.com/weaveworks/service-ui/issues/3249
* [x] ~Have sensible caps/muting to avoid email overload~ https://github.com/weaveworks/service/issues/2299
* [x] ~Encourage users in the email to set up slack integration~  https://github.com/weaveworks/service/issues/2297
* [x] ~Revise the wording of all notification emails~ https://github.com/weaveworks/service/issues/2298

Try splitting this into a bunch of smaller issues.
