### ISSUE TITLE
Add permissions to the database

### ISSUE THREAD

**Issue by rndstr** [weaveworks/service#2398]
From the [design doc](https://docs.google.com/document/d/1omMXmK1ZrAvKIjNzOBBlteUntzRSZVcI78YgqYdPs4U/edit#heading=h.kmeo2a9lldxk):

> Names should be scoped so we can restrict the permission search, eg.. billing.view, team.list, team.write, scope.controls.terminal.view

Main verbs: `create` `view` `delete` `update`

| Namespace       | Permission                                                                                                                                                  | Name                                                 |
|-----------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------|
| Teams           | grant/remove permissions                                                                                                                                    | team.member.update                                   |
|                 | invite team members                                                                                                                                         | team.member.invite                                   |
|                 | remove team members                                                                                                                                         | team.member.remove                                   |
|                 | view team members                                                                                                                                           | team.members.view                                    |
| Instance        | delete an instance                                                                                                                                          | instance.delete                                      |
|                 | transfer an instance to another team                                                                                                                        | instance.transfer                                    |
|                 | view token                                                                                                                                                  | instance.token.view                                  |
| Notifications   | change notification settings for an instance                                                                                                                | notification.settings.update                         |
| Alerts          | edit alerting rules                                                                                                                                         | alert.settings.update                                |
| Notebooks       | create notebooks                                                                                                                                            | notebook.create                                      |
|                 | update notebooks                                                                                                                                            | notebook.update                                      |
|                 | delete notebooks                                                                                                                                            | notebook.delete                                      |
| Billing         | manage billing/credit card details                                                                                                                          | instance.billing.update                              |
| Explore (Scope) | open a shell in a host                                                                                                                                      | scope.host.exec                                      |
|                 | open a shell on a container                                                                                                                                 | scope.container.exec                                 |
|                 | attach to a running container (read access)                                                                                                                 | scope.container.attach.out                           |
|                 | attach to a running container (write access)                                                                                                                | scope.container.attach.in                            |
|                 | delete a pod                                                                                                                                                | scope.pod.delete                                     |
|                 | change the desired replica count                                                                                                                            | scope.replicas.update                                |
| Deploy (Flux)   | deploy a new image                                                                                                                                          | flux.image.deploy                                    |
|                 | change workload flux policies                                                                                                                               | flux.policy.update                                   |

#### Permissions added to the database

* [x] `team.member.invite` - #2411
* [x] `team.member.update` - #2411
* [ ] `team.member.remove` - #2468
* [ ] `team.members.view` - #2468
* [x] `instance.delete` - #2411
* [ ] `instance.transfer` - #2468
* [x] `instance.billing.update` - #2411
* [ ] `instance.token.view` - #2468
* [ ] `notification.settings.update` - #2468
* [x] `alert.settings.update` - #2411
* [ ] `notebook.create` - #2468
* [ ] `notebook.update` - #2468
* [ ] `notebook.delete` - #2468
* [ ] `scope.host.exec` - #2468
* [ ] `scope.container.exec` - #2468
* [ ] `scope.container.attach.in` - #2468
* [ ] `scope.container.attach.out` - #2468
* [ ] `scope.replicas.update` - #2468
* [ ] `scope.pod.delete` - #2468
* [ ] `flux.image.deploy` - #2468
* [ ] `flux.policy.update` - #2468
