### ISSUE TITLE
Improve UX of weekly emails

### ISSUE THREAD

**Issue by bia** [weaveworks/service#2502]
I've created this larger issue to summarise experience-related changes that and prioritise them. So far, I imagine it like : 

* [ ] Combine weekly emails into a single digest - #2524
* [x] Add tracking #2426  for
    - open rate
    - click-through rate
    - unsub rate (when we have it)
* [x] Add an unsubscribe link #2437 & #2460
* [ ] Visual improvements to weekly email #2503 
* [x] Add a call-to-action and clickable instance #2500 
* [ ] Potentially change targets for who receives what emails #2509 
* [x] Change format of emails with no content to a shorter announcement like ‘No data, no updates for this week.’ - #2500 

cc @miklosp
