### ISSUE TITLE
Add API level unit tests for all permissions

### ISSUE THREAD

**Issue by fbarl** [weaveworks/service#2527]
Follow-up to #2468.

##### Checklist

* [x] `team.member.invite` - #2471
* [x] `team.member.update` - #2471
* [x] `team.member.remove` - #2471
* [x] `team.members.view` - #2471
* [x] `instance.delete` - #2471
* [x] `instance.transfer` - #2471
* [x] `instance.token.view` - #2471
* [ ] `instance.billing.update`
* [x] `notification.settings.update` - #2547
* [x] `alert.settings.update` - #2547
* [ ] `notebook.create`
* [ ] `notebook.update`
* [ ] `notebook.delete`
* [x] `scope.host.exec` - #2547
* [x] `scope.container.exec` - #2547
* [x] `scope.container.attach` - #2547
* [x] `scope.container.stop` - #2547
* [x] `scope.container.pause` - #2547
* [x] `scope.container.restart` - #2547
* [x] `scope.replicas.update` - #2547
* [x] `scope.pod.delete` - #2547
* [x] `scope.pod.logs.view` - #2547
* [x] `flux.image.deploy` - #2547
* [x] `flux.policy.update` - #2547
* [ ] `instance.webhook.create`
* [ ] `instance.webhook.delete`
