### ISSUE TITLE
Tom's TODO List for m/t rollout

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/service#365]
- [x] remove app mapper, db etc (#390)
- [x] figure out lable & version scheme for rolling update (#371)
- [x] tear down toms cluster (#352)
- [x] ensure mt works in local (#361)

Scope m/t backnds
- add backoff into consul pipe router, gc pipes in consul (#423)
- [x] shortcut reports via SQS
- implement readiness check and graceful shutdown (#175)
- [x] report caching in dynamodb collector (https://github.com/weaveworks/scope/pull/1545)

Users service 
- add auth cache (#398)
- monitoring RDS instances (#401)
- [x] add logging (#6)

Authfe
- remove frontend, serve SSL & UI from authfe (#38)

Monitoring (#368)
- [x] alerting for m/t components
- [x] fix prom scraping services
- [x] update middleware for users service, add charts to dashboard
- [x] deploy user service w/o approval gate

Monitoring Next
- figure out a way of keeping prometheus history across upgrades (#402)
- dev alert email (#316)
- [x] build resource usage dashboard (#367)
- [x] monitoring of report size, dynamo credits (https://github.com/weaveworks/scope/pull/1545, #384)
- [x] monitoring for consul (#372)
- [x] monitoring for nginx (#372)
- [x] build yaml differ (#379)

Other people have taken:
- investigate UI performance issue (#393)
- parallelise decompress / decode (https://github.com/weaveworks/scope/pull/1554)
- memcache for reports
- [x] add admin routes to authfe
- [x] add 'admin' users
- [x] point prod probes at dev
