### ISSUE TITLE
Allow users to have multiple instances

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/service#581]
Currently a user can only have one scope instance. They may want to have more than one, and to share those instances with others.

This requires introducing the following new functionality:

As a Weave Cloud user, I should be able to
- [x] create new instances, which automatically grants me access to that instance
  - [x] API: #650 (`POST /api/users/org`)
  - [x] UI
- [x] see all instances I have access to
  - [x] API (`GET /api/users/lookup`)
  - [x] UI
- [x] view any of my instances
  - [x] API (`GET /private/api/user/lookup/{orgName}` – already called by our authenticator)
  - [x] UI
- [x] invite others to access any of my instances
  - [x] existing users (#505)
    - [x] API: #656
    - [x] UI
  - [x] people who aren't users yet
    - [x] API
    - [x] UI
- [x] see who has access to each of my instances
  - [x] API (`GET /api/users/org/{orgName}/users`, already used by the UI.)
  - [x] UI
- [x] revoke a user's access to any of my instances
  - [x] API (`DELETE /api/users/org/{orgName}/users/{userEmail}`): #661
  - [x] UI
- [x] see that I have been granted access to an instance by someone else
  - [x] API (`GET /api/users/org/{orgName}`)
  - [x] UI
- ~~revoke my own access to an instance~~ #687
  - [x] API (`DELETE /api/users/org/{orgName}/users/{myUserEmail}`): #661
  - ~~UI~~

These have some corollaries:
- [x] when I sign up to Weave Cloud for the first time, the UI should not assume that I want to create my own instance. Options include:
  - create a demo instance
  - don't create an instance automatically

Terminology note: "my instances" means "instances that I have access to" rather than "instances I have created. Having a concept of instance ownership is out of scope for this work.
