### ISSUE TITLE
Multi-app multi-team tracker issue

### ISSUE THREAD

**Issue by jml** [weaveworks/service#618]
One of our priorities for the July milestone is to have multi-app multi-team support. Exactly what this means is in flux (heh heh). This ticket is meant to represent our current understanding of what it means and what needs to be done.
## Motivation

We want to improve retention for Weave Cloud. We believe that a major reason people _stop_ using Weave Cloud is that they are unable to share instances within their organization. After all, it's rare for an individual alone to have a production system complex enough to make Scope desirable.
## Actions
- [x] #581 – Support multi-team user memberships
- [x] #505 – Cannot invite existing users to my instance
- [x] #615 – Deleting instances
- [x] #553 – Naming instances 
- [x] Clarify terminology in app
- [x] #692 – Clarify wording on invitation email
